name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build project
        run: |
          npm run build
          echo "Listing frontend directory contents:"
          ls -la ../frontend
          echo "Listing frontend/dist directory contents:"
          ls -la ../frontend/dist || echo "frontend/dist not found"
        working-directory: frontend

      - name: Check if frontend/dist exists
        run: |
          if [ ! -d "frontend/dist" ]; then
            echo "frontend/dist does not exist. Exiting."
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
